library(shiny)

ui <- fluidPage(
  tags$h1(tags$b("MPLNClust:"),"Mixtures of Multivariate Poisson-Log Normal Model for Clustering Count Data"),
  tags$hr(),
  tabsetPanel(

    # Use of the uiOutput function to create drop-down menus that update as new
    # datasets are imported or created is based on code from the following RStudio
    # Shiny tutorial: https://shiny.rstudio.com/articles/dynamic-ui.html

    # A tab that permits the user to import a dataset
    tabPanel("Step I: Import Dataset",
             sidebarLayout(
               sidebarPanel(
                 tags$p("Import a dataset of counts, such that in the dataset rows
                         should correspond to observations and columns correspond to
                         variables in .csv format. File can be previewed after
                         importing."),
                 tags$p("An example maybe created using mplnDataGenerator() function
                        of MPLNClust R package and saved into .csv format using
                        write.csv() function."),
                 fileInput("file", "Select a dataset to import:"),
                 tags$p("Enter or select values required for clustering. Default
                        values are shown."),
                 textInput("Numgmin", "Enter gmin:", "1"),
                 textInput("Numgmax", "Enter gmax:", "2"),
                 textInput("NumnChains", "Enter nChains:", "3"),
                 selectInput('TypeinitMethod',
                             'Select initMethod:',
                             c("'kmeans' ",
                               "'random' ",
                               "'medoids' ",
                               "'clara' ",
                               "'fanny' ")),
                 textInput("NumnChains", "Enter nInitIterations:", "3"),
                 selectInput('Typenormalize',
                             'Select normalize:',
                             c("'Yes' ",
                               "'No' ")),
                 textInput("numNodes", "Enter numNodes:", "NA"),
               ),
               mainPanel(tableOutput("previewTable"))
             )

    ),

    # This tab allows the user to map imported peaks onto imported features
    # using mapPeaks
    tabPanel("Step II: Clustering",
             fluidRow(
               column(4, wellPanel(
                 tags$p("Datasets imported in the previous step can be selected
                   from the following menus. After a peak dataset and a feature
                   dataset are selected from the appropriate menu, peaks can
                   be mapped onto their closest features by clicking the
                   'Map peaks onto features' button below. (This may take several
                   minutes for large datasets)"),
                 tags$p("Performing a peak-feature mapping will create a new dataset
                   of results that will remain usable until the app is closed.
                   Results can be displayed here as a table, and these results
                   can be exported as a CSV file using the 'Export' button."),
                 uiOutput("selectPeaks"),
                 uiOutput("selectFeatures"),
                 actionButton(inputId = "mappingButton", label =
                                "Map peaks onto features"),
                 textOutput("mappingMessage"),
                 tags$p(),
                 uiOutput("selectResult"),
                 actionButton(inputId = "mappingDisplayButton",
                              label = "Display selected mapping results"),
                 downloadButton("exportButton",
                                "Export selected mapping results as CSV file"),
                 tags$p(),
                 tags$p("(For proper file exporting, the filename you give this CSV
                   should end with '.csv')")
               ))),
             fluidRow(
               column(12, tableOutput("mappingTable"))
             )
    ),

    # This tab allows the user to visualize the results of mapping peaks onto
    # closest features
    tabPanel("Step III: Visualize",
             sidebarLayout(
               sidebarPanel(
                 tags$p("After mapping peaks to closest features in the previous step,
                 the generated results can be visualized here using 4 different
                 types of plots. The datasets used to create these plots can be
                 selected from the two menus below. After mapping results and
                 their corresponding peak file are selected, along with the type
                 of plot to be made, plots can be generated by clicking the
                 'Generate plot' button at the bottom of this panel. Generated
                 plots can also be saved as PNGs by clicking the 'Save' button."),
                 uiOutput("selectResultsForPlotting"),
                 uiOutput("selectPeaksForPlotting"),
                 selectInput('selectPlotType',
                             'Select the type of plot you want to make:',
                             c("1. Plot the number of closest features to each peak",
                               "2. Plot locations of mapped peaks relative to start of closest features",
                               "3. Plot distribution of overlap proportions between peaks and closest features",
                               "4. Plot distribution of qualitative peak positions relative to mapped features")),

                 tags$p("The following 5 parameters can be used to customize the
                 appearance of the generated plot. Selecting a new plot type
                 from the above menu will update the boxes for main title, x-axis
                 title, and y-axis title to the default titles for that plot
                 type."),
                 textInput("plotColor", "Enter plot color:", "Red"),
                 textInput("mainTitle", "Enter main plot title:"),
                 textInput("xTitle", "Enter plot x-axis title:"),
                 textInput("yTitle", "Enter plot y-axis title:"),
                 selectInput("backgroundStyle", "Select style of plot background:",
                             c("blackAndWhite", "grey", "minimal")),

                 tags$p("The following three parameters are only used for plotting
                 locations of mapped peaks relative to the start of closest
                 features (plot type #2 on the above list). The number of base
                 pairs plotted upstream or downstream of feature start points
                 (by default, 2500 bp) is the number of bins (default: 250)
                 times the number of bases per bin (default: 10). Fewer bases
                 per bin gives a higher resolution view of peak distribution"),

                 numericInput("upstreamBins", "Enter the number of bins (plotted points)
                       to be used upstream of each feature start position:", 250),
                 numericInput("downstreamBins", "Enter the number of bins (plotted points)
                       to be used downstream of each feature start position:", 250),
                 numericInput("basesPerBin", "Enter the width of each bin, in base pairs:", 10),
                 actionButton(inputId = "plottingButton", label = "Generate plot"),
                 downloadButton("savePlot", "Save current plot as PNG"),
                 tags$p(),
                 tags$p("(For proper plot saving, the filename you give this PNG should
                   end with '.png')")
               ),
               mainPanel(plotOutput("mainPlot", height = "750px"))
             )
    )
  )
)

server <- function(input, output, clientData, session) {

  output$mytable = DT::renderDataTable({
    output$file
  })
}

shinyApp(ui = ui, server = server)
